In [2]:
#NumPy is a Python library used for working with arrays.
#In Python we have lists that serve the purpose of arrays, but they are slow to process.
#NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
#NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and 
#manipulate them very efficiently.
import numpy as np
x = np.array([1,2,3,4,5]) #list
y = np.array((1,2,3,4,5)) #tuple
print(x)
print(y)

print(type(x))


[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
#0-D array
import numpy as np
arr = np.array(42)
print(arr)

42


In [9]:
#1-D array
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [5]:
#2-D array
import numpy as np
arr2 = np.array([[1,2,3,],[5,6,7]])
print(arr2)

[[1 2 3]
 [5 6 7]]


In [6]:
#3-D arrays
import numpy as np
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [9]:
#Access array elements
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [10]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [14]:
import numpy as np

arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0,1,2])
print(arr[1,0,2])
print(arr[0,1,1])

6
9
5


In [16]:
#print the last element from the 2nd dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [17]:
#NumPy Array Slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])



[2 3 4 5]


In [18]:
#Return every other element from the entire array:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [19]:
#Slicing 2-D Arrays
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [20]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [21]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [22]:
#DataType
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [23]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [24]:
#Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [25]:
#Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [26]:
#Change data type from float to integer by using int as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [27]:
#Change data type from integer to boolean:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [29]:
#NumPy Array Copy vs 
#The Difference Between Copy and View
#The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

import numpy as np

arr=np.array([1,2,3,4])
newarr=arr.copy()

newarr[1]=44
print(arr)
print(newarr)


[1 2 3 4]
[ 1 44  3  4]


In [30]:
#View
import numpy as np
arr=np.array([1,2,3,4])
myView= arr.view()

myView[1]=44

print(arr)
print(myView)

[ 1 44  3  4]
[ 1 44  3  4]


In [31]:
#Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [32]:
#NumPy Array Shape
#The shape of an array is the number of elements in each dimension.
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [34]:
import numpy as np
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('Shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [35]:
#Reshaping arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [37]:
#Convert the array into a 1D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [39]:
#NumPy Array Iterating
import numpy as np
arr = np.array([1,2,3,4])
for i in arr:
    print(i)

1
2
3
4


In [41]:
#Iterating 2-D Arrays
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [43]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
for i in arr:
    for x in i:
        print(x)

1
2
3
4
5
6
7
8


In [47]:
#Iterating 3-D Arrays
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print('Array -> '+ str(x))

Array -> [[1 2 3]
 [4 5 6]]
Array -> [[ 7  8  9]
 [10 11 12]]


In [51]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print('2D Array -> '+ str(x))
    for y in x:
        print('1D Array ->' + str(y))
        for z in y:
            print('0D Array -> '+str(z))
        

2D Array -> [[1 2 3]
 [4 5 6]]
1D Array ->[1 2 3]
0D Array -> 1
0D Array -> 2
0D Array -> 3
1D Array ->[4 5 6]
0D Array -> 4
0D Array -> 5
0D Array -> 6
2D Array -> [[ 7  8  9]
 [10 11 12]]
1D Array ->[7 8 9]
0D Array -> 7
0D Array -> 8
0D Array -> 9
1D Array ->[10 11 12]
0D Array -> 10
0D Array -> 11
0D Array -> 12


In [52]:
#Iterating Arrays Using nditer()
#In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [53]:
#NumPy Joining Array
#Joining means putting contents of two or more arrays in a single array.
#In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
#We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. 
#If axis is not explicitly passed, it is taken as 0 (rows are called as axis 1 and the columns are called as axis 0)
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [54]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [61]:
#Joining Arrays Using Stack Functions
#Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.concatenate((arr1, arr2))
arr4 = np.stack((arr1, arr2), axis=0)
arr5 = np.stack((arr1, arr2), axis=1)

print(arr3)
print(arr4)
print(arr5)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [62]:
#Stacking Along Rows
#NumPy provides a helper function: hstack() to stack along rows.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [64]:
#NumPy Splitting Array
#Splitting is reverse operation of Joining.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [65]:
#Split the array in 4 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [67]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [68]:
#Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [69]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [70]:
#Split the 2-D array into three 2-D arrays along rows.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [71]:
#NumPy Searching Arrays
#Find the indexes where the value is 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [72]:
#Find the indexes where the values are even:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [73]:
#Find the indexes where the values are odd:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [75]:
#Search Sorted
#Find the indexes where the value 7 should be inserted:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [76]:
#NumPy Sorting Arrays
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [77]:
#Sort a 2-D array:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [78]:
#NumPy Filter Array
# In NumPy, you filter an array using a boolean index list.
#A boolean index list is a list of booleans corresponding to indexes in the array.
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [80]:
#Creating Filter Directly From Array
#Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [81]:
#Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [93]:
#Aggregation
import numpy as np
arr = np.array([1,2,3,4])
print(arr.sum())
print(arr.min())

arr2=np.array([[1,2],[1,3],[1,2]])
print(arr2)
print(arr2.sum(axis=0))

10
1
[[1 2]
 [1 3]
 [1 2]]
[3 7]


In [90]:
#Other functions
import numpy as np

print(np.ones((3,2)))
print(np.zeros((2,2)))
print(np.random.random((4,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[0.44267222 0.824495  ]
 [0.48590489 0.53253837]
 [0.3813692  0.90420168]
 [0.91543343 0.15996588]]
